import type { Metadata } from "next";
import { Rubik, Rubik_Mono_One } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "@/components/app-sidebar";

const font = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const fontMono = Rubik_Mono_One({
  variable: "--font-rubik-mono",
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "OFFShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} ${fontMono.variable} antialiased`}
      >
        <Providers>
          <AppSideBar />
          <div className='flex flex-1 flex-col max-w-screen overflow-hidden'>
            <header className='bg-card sticky top-0 z-50 flex h-13.75 items-center justify-between gap-6 border-b px-4 py-2 sm:px-6'>
              <SidebarTrigger className='[&_svg]:size-5!' />
            </header>
            <main className='size-full flex-1 px-4 py-6 sm:px- w-full'>
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html >
  );
}
